language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 5.2
    - php: 5.3
    - php: 7.0
    - php: hhvm
    - nightly

script: phpunit --configuration test/phpunit.xml --coverage-text

install:
  - composer install

