---
sudo: required

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != '5.3' ]; then printf "\n" | pecl install imagick; fi"
  - mkdir -p build/logs/

script:
  - php -m
  - php vendor/bin/phpcs --standard=psr2 src/ -n
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - wget -c -nc https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar -v
...
